server:
  port: 9093
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  main:
    web-application-type: REACTIVE
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/customer/**
        - id: current-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/currentAccount/**
        
        
            
            
management:
  endpoints:
    web:
      exposures:
        include: "*"
